### RPM lcg genser-tool-conf CMS_148a8
# DO NOT MODIFY. This spec file is automatically generated by executing src/createConfSpecs.sh in the 
# main directory. Modify src/toolConfiguration.xsl if needed.

# We set a special variable TOOLCONF_VERSION which is then used by scram-build.file and scramv1-build.file to
# check out the correct toolbox. Notice that all the *-tool-conf.spec set the same variable so this is 
# relevant only for build time and not for runtime.
## INITENV SET TOOLCONF_VERSION %{v}
Source0: none

Requires: gcc
Requires: boost
Requires: bz2lib
Requires: clhep
Requires: cppunit
Requires: gccxml
Requires: gsl
Requires: hepmc
Requires: oval
Requires: pcre
Requires: python
Requires: uuid
Requires: valgrind
Requires: zlib
%prep
%build
(echo "ARCHITECTURE:%{cmsplatf}"
 echo "SCRAM_BASEPATH:%{instroot}/external"

%define is_arch_slc3_ia32_gcc344_dbg %(if [ `echo "%{cmsplatf}" | sed -e 's/\(slc3_ia32_gcc344_dbg\)/\1/'` = "%{cmsplatf}" ]; then echo true; else echo false; fi)
%if "%is_arch_slc3_ia32_gcc344_dbg" == "true"

%if "%{?use_system_gcc:set}" == "set"
  echo "TOOL:gcc344:"
       echo "  +GCC_BASE:/none"
       echo "  +CC:$(which gcc)"
       echo "  +CXX:$(which c++)"
       echo "  +PATH:/none"  # useless, toolbox says value=""
       echo "  +LD_LIBRARY_PATH:/none" # useless, toolbox says value=""
       echo "TOOL:g77gcc3:"
       echo "  +FC:$(which g77 | grep -v 'no g77')"
%endif
%if "%{?use_system_gcc:set}-%{?use_ccache:set}" == "-set"
echo "TOOL:gcc344:"
       echo "  +GCC_BASE:$CCACHE_ROOT"
eval        "echo \"  +CC:$CCACHE_ROOT/bin/gcc\""
eval        "echo \"  +CXX:$CCACHE_ROOT/bin/c++\""
       echo "TOOL:g77gcc3:"
       echo "  +FC:$GCC_ROOT/bin/g77"
%endif
%if "%{?use_system_gcc:set}-%{?use_ccache:set}" == "-" 
echo "TOOL:gcc344:"
       echo "  +GCC_BASE:$GCC_ROOT"
       echo "TOOL:g77gcc3:"
       echo "  +FC:$GCC_ROOT/bin/g77"
%endif

%endif 

%define is_arch_slc3_ia32_gcc344 %(if [ `echo "%{cmsplatf}" | sed -e 's/\(slc3_ia32_gcc344\)/\1/'` = "%{cmsplatf}" ]; then echo true; else echo false; fi)
%if "%is_arch_slc3_ia32_gcc344" == "true"

%if "%{?use_system_gcc:set}" == "set"
  echo "TOOL:gcc344:"
       echo "  +GCC_BASE:/none"
       echo "  +CC:$(which gcc)"
       echo "  +CXX:$(which c++)"
       echo "  +PATH:/none"  # useless, toolbox says value=""
       echo "  +LD_LIBRARY_PATH:/none" # useless, toolbox says value=""
       echo "TOOL:g77gcc3:"
       echo "  +FC:$(which g77 | grep -v 'no g77')"
%endif
%if "%{?use_system_gcc:set}-%{?use_ccache:set}" == "-set"
echo "TOOL:gcc344:"
       echo "  +GCC_BASE:$CCACHE_ROOT"
eval        "echo \"  +CC:$CCACHE_ROOT/bin/gcc\""
eval        "echo \"  +CXX:$CCACHE_ROOT/bin/c++\""
       echo "TOOL:g77gcc3:"
       echo "  +FC:$GCC_ROOT/bin/g77"
%endif
%if "%{?use_system_gcc:set}-%{?use_ccache:set}" == "-" 
echo "TOOL:gcc344:"
       echo "  +GCC_BASE:$GCC_ROOT"
       echo "TOOL:g77gcc3:"
       echo "  +FC:$GCC_ROOT/bin/g77"
%endif

%endif 

%define is_arch_slc3_ia32_gcc323_dbg %(if [ `echo "%{cmsplatf}" | sed -e 's/\(slc3_ia32_gcc323_dbg\)/\1/'` = "%{cmsplatf}" ]; then echo true; else echo false; fi)
%if "%is_arch_slc3_ia32_gcc323_dbg" == "true"

%if "%{?use_system_gcc:set}" == "set"
  echo "TOOL:gcc3:"
       echo "  +GCC_BASE:/none"
       echo "  +CC:$(which gcc)"
       echo "  +CXX:$(which c++)"
       echo "  +PATH:/none"  # useless, toolbox says value=""
       echo "  +LD_LIBRARY_PATH:/none" # useless, toolbox says value=""
       echo "TOOL:g77gcc3:"
       echo "  +FC:$(which g77 | grep -v 'no g77')"
%endif
%if "%{?use_system_gcc:set}-%{?use_ccache:set}" == "-set"
echo "TOOL:gcc3:"
       echo "  +GCC_BASE:$CCACHE_ROOT"
eval        "echo \"  +CC:$CCACHE_ROOT/bin/gcc\""
eval        "echo \"  +CXX:$CCACHE_ROOT/bin/c++\""
       echo "TOOL:g77gcc3:"
       echo "  +FC:$GCC_ROOT/bin/g77"
%endif
%if "%{?use_system_gcc:set}-%{?use_ccache:set}" == "-" 
echo "TOOL:gcc3:"
       echo "  +GCC_BASE:$GCC_ROOT"
       echo "TOOL:g77gcc3:"
       echo "  +FC:$GCC_ROOT/bin/g77"
%endif

%endif 

%define is_arch_slc3_ia32_gcc323 %(if [ `echo "%{cmsplatf}" | sed -e 's/\(slc3_ia32_gcc323\)/\1/'` = "%{cmsplatf}" ]; then echo true; else echo false; fi)
%if "%is_arch_slc3_ia32_gcc323" == "true"

%if "%{?use_system_gcc:set}" == "set"
  echo "TOOL:gcc3:"
       echo "  +GCC_BASE:/none"
       echo "  +CC:$(which gcc)"
       echo "  +CXX:$(which c++)"
       echo "  +PATH:/none"  # useless, toolbox says value=""
       echo "  +LD_LIBRARY_PATH:/none" # useless, toolbox says value=""
       echo "TOOL:g77gcc3:"
       echo "  +FC:$(which g77 | grep -v 'no g77')"
%endif
%if "%{?use_system_gcc:set}-%{?use_ccache:set}" == "-set"
echo "TOOL:gcc3:"
       echo "  +GCC_BASE:$CCACHE_ROOT"
eval        "echo \"  +CC:$CCACHE_ROOT/bin/gcc\""
eval        "echo \"  +CXX:$CCACHE_ROOT/bin/c++\""
       echo "TOOL:g77gcc3:"
       echo "  +FC:$GCC_ROOT/bin/g77"
%endif
%if "%{?use_system_gcc:set}-%{?use_ccache:set}" == "-" 
echo "TOOL:gcc3:"
       echo "  +GCC_BASE:$GCC_ROOT"
       echo "TOOL:g77gcc3:"
       echo "  +FC:$GCC_ROOT/bin/g77"
%endif

%endif 

%define is_arch_rh73_gcc323_dbg %(if [ `echo "%{cmsplatf}" | sed -e 's/\(rh73_gcc323_dbg\)/\1/'` = "%{cmsplatf}" ]; then echo true; else echo false; fi)
%if "%is_arch_rh73_gcc323_dbg" == "true"

%if "%{?use_system_gcc:set}" == "set"
  echo "TOOL:gcc3:"
       echo "  +GCC_BASE:/none"
       echo "  +CC:$(which gcc)"
       echo "  +CXX:$(which c++)"
       echo "  +PATH:/none"  # useless, toolbox says value=""
       echo "  +LD_LIBRARY_PATH:/none" # useless, toolbox says value=""
       echo "TOOL:g77gcc3:"
       echo "  +FC:$(which g77 | grep -v 'no g77')"
%endif
%if "%{?use_system_gcc:set}-%{?use_ccache:set}" == "-set"
echo "TOOL:gcc3:"
       echo "  +GCC_BASE:$CCACHE_ROOT"
eval        "echo \"  +CC:$CCACHE_ROOT/bin/gcc\""
eval        "echo \"  +CXX:$CCACHE_ROOT/bin/c++\""
       echo "TOOL:g77gcc3:"
       echo "  +FC:$GCC_ROOT/bin/g77"
%endif
%if "%{?use_system_gcc:set}-%{?use_ccache:set}" == "-" 
echo "TOOL:gcc3:"
       echo "  +GCC_BASE:$GCC_ROOT"
       echo "TOOL:g77gcc3:"
       echo "  +FC:$GCC_ROOT/bin/g77"
%endif

%endif 

%define is_arch_rh73_gcc323 %(if [ `echo "%{cmsplatf}" | sed -e 's/\(rh73_gcc323\)/\1/'` = "%{cmsplatf}" ]; then echo true; else echo false; fi)
%if "%is_arch_rh73_gcc323" == "true"

%if "%{?use_system_gcc:set}" == "set"
  echo "TOOL:gcc3:"
       echo "  +GCC_BASE:/none"
       echo "  +CC:$(which gcc)"
       echo "  +CXX:$(which c++)"
       echo "  +PATH:/none"  # useless, toolbox says value=""
       echo "  +LD_LIBRARY_PATH:/none" # useless, toolbox says value=""
       echo "TOOL:g77gcc3:"
       echo "  +FC:$(which g77 | grep -v 'no g77')"
%endif
%if "%{?use_system_gcc:set}-%{?use_ccache:set}" == "-set"
echo "TOOL:gcc3:"
       echo "  +GCC_BASE:$CCACHE_ROOT"
eval        "echo \"  +CC:$CCACHE_ROOT/bin/gcc\""
eval        "echo \"  +CXX:$CCACHE_ROOT/bin/c++\""
       echo "TOOL:g77gcc3:"
       echo "  +FC:$GCC_ROOT/bin/g77"
%endif
%if "%{?use_system_gcc:set}-%{?use_ccache:set}" == "-" 
echo "TOOL:gcc3:"
       echo "  +GCC_BASE:$GCC_ROOT"
       echo "TOOL:g77gcc3:"
       echo "  +FC:$GCC_ROOT/bin/g77"
%endif

%endif 

%define is_arch_rh73_gcc32_dbg %(if [ `echo "%{cmsplatf}" | sed -e 's/\(rh73_gcc32_dbg\)/\1/'` = "%{cmsplatf}" ]; then echo true; else echo false; fi)
%if "%is_arch_rh73_gcc32_dbg" == "true"

%if "%{?use_system_gcc:set}" == "set"
  echo "TOOL:gcc3:"
       echo "  +GCC_BASE:/none"
       echo "  +CC:$(which gcc)"
       echo "  +CXX:$(which c++)"
       echo "  +PATH:/none"  # useless, toolbox says value=""
       echo "  +LD_LIBRARY_PATH:/none" # useless, toolbox says value=""
       echo "TOOL:g77gcc3:"
       echo "  +FC:$(which g77 | grep -v 'no g77')"
%endif
%if "%{?use_system_gcc:set}-%{?use_ccache:set}" == "-set"
echo "TOOL:gcc3:"
       echo "  +GCC_BASE:$CCACHE_ROOT"
eval        "echo \"  +CC:$CCACHE_ROOT/bin/gcc\""
eval        "echo \"  +CXX:$CCACHE_ROOT/bin/c++\""
       echo "TOOL:g77gcc3:"
       echo "  +FC:$GCC_ROOT/bin/g77"
%endif
%if "%{?use_system_gcc:set}-%{?use_ccache:set}" == "-" 
echo "TOOL:gcc3:"
       echo "  +GCC_BASE:$GCC_ROOT"
       echo "TOOL:g77gcc3:"
       echo "  +FC:$GCC_ROOT/bin/g77"
%endif

%endif 

%define is_arch_rh73_gcc32 %(if [ `echo "%{cmsplatf}" | sed -e 's/\(rh73_gcc32\)/\1/'` = "%{cmsplatf}" ]; then echo true; else echo false; fi)
%if "%is_arch_rh73_gcc32" == "true"

%if "%{?use_system_gcc:set}" == "set"
  echo "TOOL:gcc3:"
       echo "  +GCC_BASE:/none"
       echo "  +CC:$(which gcc)"
       echo "  +CXX:$(which c++)"
       echo "  +PATH:/none"  # useless, toolbox says value=""
       echo "  +LD_LIBRARY_PATH:/none" # useless, toolbox says value=""
       echo "TOOL:g77gcc3:"
       echo "  +FC:$(which g77 | grep -v 'no g77')"
%endif
%if "%{?use_system_gcc:set}-%{?use_ccache:set}" == "-set"
echo "TOOL:gcc3:"
       echo "  +GCC_BASE:$CCACHE_ROOT"
eval        "echo \"  +CC:$CCACHE_ROOT/bin/gcc\""
eval        "echo \"  +CXX:$CCACHE_ROOT/bin/c++\""
       echo "TOOL:g77gcc3:"
       echo "  +FC:$GCC_ROOT/bin/g77"
%endif
%if "%{?use_system_gcc:set}-%{?use_ccache:set}" == "-" 
echo "TOOL:gcc3:"
       echo "  +GCC_BASE:$GCC_ROOT"
       echo "TOOL:g77gcc3:"
       echo "  +FC:$GCC_ROOT/bin/g77"
%endif

%endif 

%define is_arch_Linux__2.4 %(if [ `echo "%{cmsplatf}" | sed -e 's/\(Linux__2.4\)/\1/'` = "%{cmsplatf}" ]; then echo true; else echo false; fi)
%if "%is_arch_Linux__2.4" == "true"

%if "%{?use_system_gcc:set}" == "set"
  echo "TOOL:gcc3:"
       echo "  +GCC_BASE:/none"
       echo "  +CC:$(which gcc)"
       echo "  +CXX:$(which c++)"
       echo "  +PATH:/none"  # useless, toolbox says value=""
       echo "  +LD_LIBRARY_PATH:/none" # useless, toolbox says value=""
       echo "TOOL:g77gcc3:"
       echo "  +FC:$(which g77 | grep -v 'no g77')"
%endif
%if "%{?use_system_gcc:set}-%{?use_ccache:set}" == "-set"
echo "TOOL:gcc3:"
       echo "  +GCC_BASE:$CCACHE_ROOT"
eval        "echo \"  +CC:$CCACHE_ROOT/bin/gcc\""
eval        "echo \"  +CXX:$CCACHE_ROOT/bin/c++\""
       echo "TOOL:g77gcc3:"
       echo "  +FC:$GCC_ROOT/bin/g77"
%endif
%if "%{?use_system_gcc:set}-%{?use_ccache:set}" == "-" 
echo "TOOL:gcc3:"
       echo "  +GCC_BASE:$GCC_ROOT"
       echo "TOOL:g77gcc3:"
       echo "  +FC:$GCC_ROOT/bin/g77"
%endif

%endif 

%define is_arch_rh73_icc71 %(if [ `echo "%{cmsplatf}" | sed -e 's/\(rh73_icc71\)/\1/'` = "%{cmsplatf}" ]; then echo true; else echo false; fi)
%if "%is_arch_rh73_icc71" == "true"


echo "TOOL:icc:"
eval "echo \"  +ICC_BASE:\${ICC_ROOT}\""
eval "echo \"  +PATH:\${ICC_ROOT}/bin\""
eval "echo \"  +LIBDIR:\${ICC_ROOT}/lib\""
eval "echo \"  +INCLUDE:\${ICC_ROOT}/include\""


echo "TOOL:ifc:"
eval "echo \"  +IFC_BASE:\${IFC_ROOT}\""
eval "echo \"  +PATH:\${IFC_ROOT}/bin\""
eval "echo \"  +LIBDIR:\${IFC_ROOT}/lib\""
eval "echo \"  +INCLUDE:\${IFC_ROOT}/include\""

%endif 

%define is_arch_rh73_gcc2952 %(if [ `echo "%{cmsplatf}" | sed -e 's/\(rh73_gcc2952\)/\1/'` = "%{cmsplatf}" ]; then echo true; else echo false; fi)
%if "%is_arch_rh73_gcc2952" == "true"


echo "TOOL:gcc:"
eval "echo \"  +GCC_BASE:\${GCC_ROOT}\""
eval "echo \"  +PATH:\${GCC_ROOT}/bin\""
eval "echo \"  +LIBDIR:\${GCC_ROOT}/lib\""
eval "echo \"  +INCLUDE:\${GCC_ROOT}/include\""


echo "TOOL:g77:"
eval "echo \"  +G77_BASE:\${G77_ROOT}\""
eval "echo \"  +PATH:\${G77_ROOT}/bin\""
eval "echo \"  +LIBDIR:\${G77_ROOT}/lib\""
eval "echo \"  +INCLUDE:\${G77_ROOT}/include\""

%endif 

%define is_arch_rh73_gcc323 %(if [ `echo "%{cmsplatf}" | sed -e 's/\(rh73_gcc323\)/\1/'` = "%{cmsplatf}" ]; then echo true; else echo false; fi)
%if "%is_arch_rh73_gcc323" == "true"


echo "TOOL:evtgenlhcb:"
eval "echo \"  +EVTGENLHCB_BASE:\${EVTGENLHCB_ROOT}\""
eval "echo \"  +PATH:\${EVTGENLHCB_ROOT}/bin\""
eval "echo \"  +LIBDIR:\${EVTGENLHCB_ROOT}/lib\""
eval "echo \"  +INCLUDE:\${EVTGENLHCB_ROOT}/include\""

%endif 

%define is_arch_rh73_gcc32 %(if [ `echo "%{cmsplatf}" | sed -e 's/\(rh73_gcc32\)/\1/'` = "%{cmsplatf}" ]; then echo true; else echo false; fi)
%if "%is_arch_rh73_gcc32" == "true"


echo "TOOL:comphep:"
eval "echo \"  +COMPHEP_BASE:\${COMPHEP_ROOT}\""
eval "echo \"  +PATH:\${COMPHEP_ROOT}/bin\""
eval "echo \"  +LIBDIR:\${COMPHEP_ROOT}/lib\""
eval "echo \"  +INCLUDE:\${COMPHEP_ROOT}/include\""


echo "TOOL:evtgen:"
eval "echo \"  +EVTGEN_BASE:\${EVTGEN_ROOT}\""
eval "echo \"  +PATH:\${EVTGEN_ROOT}/bin\""
eval "echo \"  +LIBDIR:\${EVTGEN_ROOT}/lib\""
eval "echo \"  +INCLUDE:\${EVTGEN_ROOT}/include\""

%endif 


echo "TOOL:boost:"
eval "echo \"  +BOOST_BASE:\${BOOST_ROOT}\""
eval "echo \"  +PATH:\${BOOST_ROOT}/bin\""
eval "echo \"  +LIBDIR:\${BOOST_ROOT}/lib\""
eval "echo \"  +INCLUDE:\${BOOST_ROOT}/include\""


echo "TOOL:bz2lib:"
eval "echo \"  +BZ2LIB_BASE:\${BZ2LIB_ROOT}\""
eval "echo \"  +PATH:\${BZ2LIB_ROOT}/bin\""
eval "echo \"  +LIBDIR:\${BZ2LIB_ROOT}/lib\""
eval "echo \"  +INCLUDE:\${BZ2LIB_ROOT}/include\""


echo "TOOL:cernlib:"
eval "echo \"  +CERNLIB_BASE:\${CERNLIB_ROOT}\""
eval "echo \"  +PATH:\${CERNLIB_ROOT}/bin\""
eval "echo \"  +LIBDIR:\${CERNLIB_ROOT}/lib\""
eval "echo \"  +INCLUDE:\${CERNLIB_ROOT}/include\""


echo "TOOL:clhep:"
eval "echo \"  +CLHEP_BASE:\${CLHEP_ROOT}\""
eval "echo \"  +PATH:\${CLHEP_ROOT}/bin\""
eval "echo \"  +LIBDIR:\${CLHEP_ROOT}/lib\""
eval "echo \"  +INCLUDE:\${CLHEP_ROOT}/include\""


echo "TOOL:cppunit:"
eval "echo \"  +CPPUNIT_BASE:\${CPPUNIT_ROOT}\""
eval "echo \"  +PATH:\${CPPUNIT_ROOT}/bin\""
eval "echo \"  +LIBDIR:\${CPPUNIT_ROOT}/lib\""
eval "echo \"  +INCLUDE:\${CPPUNIT_ROOT}/include\""


echo "TOOL:gccxml:"
eval "echo \"  +GCCXML_BASE:\${GCCXML_ROOT}\""
eval "echo \"  +PATH:\${GCCXML_ROOT}/bin\""
eval "echo \"  +LIBDIR:\${GCCXML_ROOT}/lib\""
eval "echo \"  +INCLUDE:\${GCCXML_ROOT}/include\""


echo "TOOL:gsl:"
eval "echo \"  +GSL_BASE:\${GSL_ROOT}\""
eval "echo \"  +PATH:\${GSL_ROOT}/bin\""
eval "echo \"  +LIBDIR:\${GSL_ROOT}/lib\""
eval "echo \"  +INCLUDE:\${GSL_ROOT}/include\""


echo "TOOL:hepmc:"
eval "echo \"  +HEPMC_BASE:\${HEPMC_ROOT}\""
eval "echo \"  +PATH:\${HEPMC_ROOT}/bin\""
eval "echo \"  +LIBDIR:\${HEPMC_ROOT}/lib\""
eval "echo \"  +INCLUDE:\${HEPMC_ROOT}/include\""


echo "TOOL:oval:"
eval "echo \"  +OVAL_BASE:\${OVAL_ROOT}\""
eval "echo \"  +PATH:\${OVAL_ROOT}/bin\""
eval "echo \"  +LIBDIR:\${OVAL_ROOT}/lib\""
eval "echo \"  +INCLUDE:\${OVAL_ROOT}/include\""


echo "TOOL:pcre:"
eval "echo \"  +PCRE_BASE:\${PCRE_ROOT}\""
eval "echo \"  +PATH:\${PCRE_ROOT}/bin\""
eval "echo \"  +LIBDIR:\${PCRE_ROOT}/lib\""
eval "echo \"  +INCLUDE:\${PCRE_ROOT}/include\""

PYTHON_MAJOR=$(echo $PYTHON_VERSION | sed 's/\.[0-9]*$//')
echo "TOOL:python:"
echo "  +PYTHON_BASE:$PYTHON_ROOT"
echo "  +LIBDIR:$PYTHON_ROOT/lib"
echo "  +INCLUDE:$PYTHON_ROOT/include/python$PYTHON_MAJOR"
echo "  +PATH:$PYTHON_ROOT/bin"

echo "TOOL:uuid:"
eval "echo \"  +UUID_BASE:\${UUID_ROOT}\""
eval "echo \"  +PATH:\${UUID_ROOT}/bin\""
eval "echo \"  +LIBDIR:\${UUID_ROOT}/lib\""
eval "echo \"  +INCLUDE:\${UUID_ROOT}/include\""


echo "TOOL:valgrind:"
eval "echo \"  +VALGRIND_BASE:\${VALGRIND_ROOT}\""
eval "echo \"  +PATH:\${VALGRIND_ROOT}/bin\""
eval "echo \"  +LIBDIR:\${VALGRIND_ROOT}/lib\""
eval "echo \"  +INCLUDE:\${VALGRIND_ROOT}/include\""


echo "TOOL:zlib:"
eval "echo \"  +ZLIB_BASE:\${ZLIB_ROOT}\""
eval "echo \"  +PATH:\${ZLIB_ROOT}/bin\""
eval "echo \"  +LIBDIR:\${ZLIB_ROOT}/lib\""
eval "echo \"  +INCLUDE:\${ZLIB_ROOT}/include\""

) > tools.conf
%install
mkdir %i/configurations/
cp tools.conf %i/configurations/tools-STANDALONE.conf
%post
%{relocateConfig}configurations/tools-STANDALONE.conf
