### RPM virtual glibc 2.3.2
Source: none
Provides: ANSI_X3.110.so  
Provides: ARMSCII-8.so  
Provides: ASMO_449.so  
Provides: BIG5.so  
Provides: BIG5HKSCS.so  
Provides: CP10007.so  
Provides: CP1125.so  
Provides: CP1250.so  
Provides: CP1251.so  
Provides: CP1252.so  
Provides: CP1253.so  
Provides: CP1254.so  
Provides: CP1255.so  
Provides: CP1256.so  
Provides: CP1257.so  
Provides: CP1258.so  
Provides: CP737.so  
Provides: CP775.so  
Provides: CP932.so  
Provides: CSN_369103.so  
Provides: CWI.so  
Provides: DEC-MCS.so  
Provides: EBCDIC-AT-DE-A.so  
Provides: EBCDIC-AT-DE.so  
Provides: EBCDIC-CA-FR.so  
Provides: EBCDIC-DK-NO-A.so  
Provides: EBCDIC-DK-NO.so  
Provides: EBCDIC-ES-A.so  
Provides: EBCDIC-ES-S.so  
Provides: EBCDIC-ES.so  
Provides: EBCDIC-FI-SE-A.so  
Provides: EBCDIC-FI-SE.so  
Provides: EBCDIC-FR.so  
Provides: EBCDIC-IS-FRISS.so  
Provides: EBCDIC-IT.so  
Provides: EBCDIC-PT.so  
Provides: EBCDIC-UK.so  
Provides: EBCDIC-US.so  
Provides: ECMA-CYRILLIC.so  
Provides: EUC-CN.so  
Provides: EUC-JISX0213.so  
Provides: EUC-JP-MS.so  
Provides: EUC-JP.so  
Provides: EUC-KR.so  
Provides: EUC-TW.so  
Provides: GB18030.so  
Provides: GBBIG5.so  
Provides: GBGBK.so  
Provides: GBK.so  
Provides: GEORGIAN-ACADEMY.so  
Provides: GEORGIAN-PS.so  
Provides: GOST_19768-74.so  
Provides: GREEK-CCITT.so  
Provides: GREEK7-OLD.so  
Provides: GREEK7.so  
Provides: HP-ROMAN8.so  
Provides: IBM037.so  
Provides: IBM038.so  
Provides: IBM1004.so  
Provides: IBM1026.so  
Provides: IBM1046.so  
Provides: IBM1047.so  
Provides: IBM1124.so  
Provides: IBM1129.so  
Provides: IBM1132.so  
Provides: IBM1133.so  
Provides: IBM1160.so  
Provides: IBM1161.so  
Provides: IBM1162.so  
Provides: IBM1163.so  
Provides: IBM1164.so  
Provides: IBM256.so  
Provides: IBM273.so  
Provides: IBM274.so  
Provides: IBM275.so  
Provides: IBM277.so  
Provides: IBM278.so  
Provides: IBM280.so  
Provides: IBM281.so  
Provides: IBM284.so  
Provides: IBM285.so  
Provides: IBM290.so  
Provides: IBM297.so  
Provides: IBM420.so  
Provides: IBM423.so  
Provides: IBM424.so  
Provides: IBM437.so  
Provides: IBM500.so  
Provides: IBM850.so  
Provides: IBM851.so  
Provides: IBM852.so  
Provides: IBM855.so  
Provides: IBM856.so  
Provides: IBM857.so  
Provides: IBM860.so  
Provides: IBM861.so  
Provides: IBM862.so  
Provides: IBM863.so  
Provides: IBM864.so  
Provides: IBM865.so  
Provides: IBM866.so  
Provides: IBM866NAV.so  
Provides: IBM868.so  
Provides: IBM869.so  
Provides: IBM870.so  
Provides: IBM871.so  
Provides: IBM874.so  
Provides: IBM875.so  
Provides: IBM880.so  
Provides: IBM891.so  
Provides: IBM903.so  
Provides: IBM904.so  
Provides: IBM905.so  
Provides: IBM918.so  
Provides: IBM922.so  
Provides: IBM930.so  
Provides: IBM932.so  
Provides: IBM933.so  
Provides: IBM935.so  
Provides: IBM937.so  
Provides: IBM939.so  
Provides: IBM943.so  
Provides: IEC_P27-1.so  
Provides: INIS-8.so  
Provides: INIS-CYRILLIC.so  
Provides: INIS.so  
Provides: ISIRI-3342.so  
Provides: ISO-2022-CN-EXT.so  
Provides: ISO-2022-CN.so  
Provides: ISO-2022-JP-3.so  
Provides: ISO-2022-JP.so  
Provides: ISO-2022-KR.so  
Provides: ISO-IR-197.so  
Provides: ISO-IR-209.so  
Provides: ISO646.so  
Provides: ISO8859-1.so  
Provides: ISO8859-10.so  
Provides: ISO8859-11.so  
Provides: ISO8859-13.so  
Provides: ISO8859-14.so  
Provides: ISO8859-15.so  
Provides: ISO8859-16.so  
Provides: ISO8859-2.so  
Provides: ISO8859-3.so  
Provides: ISO8859-4.so  
Provides: ISO8859-5.so  
Provides: ISO8859-6.so  
Provides: ISO8859-7.so  
Provides: ISO8859-8.so  
Provides: ISO8859-9.so  
Provides: ISO_10367-BOX.so  
Provides: ISO_2033.so  
Provides: ISO_5427-EXT.so  
Provides: ISO_5427.so  
Provides: ISO_5428.so  
Provides: ISO_6937-2.so  
Provides: ISO_6937.so  
Provides: JOHAB.so  
Provides: KOI-8.so  
Provides: KOI8-R.so  
Provides: KOI8-T.so  
Provides: KOI8-U.so  
Provides: LATIN-GREEK-1.so  
Provides: LATIN-GREEK.so  
Provides: MAC-IS.so  
Provides: MAC-SAMI.so  
Provides: MAC-UK.so  
Provides: MACINTOSH.so  
Provides: NATS-DANO.so  
Provides: NATS-SEFI.so  
Provides: SAMI-WS2.so  
Provides: SHIFT_JISX0213.so  
Provides: SJIS.so  
Provides: T.61.so  
Provides: TCVN5712-1.so  
Provides: TIS-620.so  
Provides: TSCII.so  
Provides: UHC.so  
Provides: UNICODE.so  
Provides: UTF-16.so  
Provides: UTF-32.so  
Provides: UTF-7.so  
Provides: VISCII.so  
Provides: config(glibc) 
Provides: ld-linux.so.2  
Provides: ld-linux.so.2(GLIBC_2.0)  
Provides: ld-linux.so.2(GLIBC_2.1)  
Provides: ld-linux.so.2(GLIBC_2.3)  
Provides: ldconfig  
Provides: libBrokenLocale.so.1  
Provides: libBrokenLocale.so.1(GLIBC_2.0)  
Provides: libCNS.so  
Provides: libGB.so  
Provides: libISOIR165.so  
Provides: libJIS.so  
Provides: libJISX0213.so  
Provides: libKSC.so  
Provides: libNoVersion.so.1  
Provides: libSegFault.so  
Provides: libanl.so.1  
Provides: libanl.so.1(GLIBC_2.2.3)  
Provides: libc.so.6  
Provides: libc.so.6(GCC_3.0)  
Provides: libc.so.6(GLIBC_2.0)  
Provides: libc.so.6(GLIBC_2.1)  
Provides: libc.so.6(GLIBC_2.1.1)  
Provides: libc.so.6(GLIBC_2.1.2)  
Provides: libc.so.6(GLIBC_2.1.3)  
Provides: libc.so.6(GLIBC_2.2)  
Provides: libc.so.6(GLIBC_2.2.1)  
Provides: libc.so.6(GLIBC_2.2.2)  
Provides: libc.so.6(GLIBC_2.2.3)  
Provides: libc.so.6(GLIBC_2.2.4)  
Provides: libc.so.6(GLIBC_2.2.6)  
Provides: libc.so.6(GLIBC_2.3)  
Provides: libc.so.6(GLIBC_2.3.2)  
Provides: libc.so.6(GLIBC_2.3.3)  
Provides: libcrypt.so.1  
Provides: libcrypt.so.1(GLIBC_2.0)  
Provides: libdl.so.2  
Provides: libdl.so.2(GLIBC_2.0)  
Provides: libdl.so.2(GLIBC_2.1)  
Provides: libdl.so.2(GLIBC_2.3.3)  
Provides: libm.so.6  
Provides: libm.so.6(GLIBC_2.0)  
Provides: libm.so.6(GLIBC_2.1)  
Provides: libm.so.6(GLIBC_2.2)  
Provides: libnsl.so.1  
Provides: libnsl.so.1(GLIBC_2.0)  
Provides: libnsl.so.1(GLIBC_2.1)  
Provides: libnsl.so.1(GLIBC_2.2)  
Provides: libnss_compat.so.1  
Provides: libnss_compat.so.1(GLIBC_2.0)  
Provides: libnss_compat.so.2  
Provides: libnss_dns.so.1  
Provides: libnss_dns.so.1(GLIBC_2.0)  
Provides: libnss_dns.so.2  
Provides: libnss_files.so.1  
Provides: libnss_files.so.1(GLIBC_2.0)  
Provides: libnss_files.so.2  
Provides: libnss_hesiod.so.2  
Provides: libnss_nis.so.1  
Provides: libnss_nis.so.1(GLIBC_2.0)  
Provides: libnss_nis.so.2  
Provides: libnss_nisplus.so.2  
Provides: libpthread.so.0  
Provides: libpthread.so.0(GLIBC_2.0)  
Provides: libpthread.so.0(GLIBC_2.1)  
Provides: libpthread.so.0(GLIBC_2.1.1)  
Provides: libpthread.so.0(GLIBC_2.1.2)  
Provides: libpthread.so.0(GLIBC_2.2)  
Provides: libpthread.so.0(GLIBC_2.2.3)  
Provides: libpthread.so.0(GLIBC_2.2.6)  
Provides: libpthread.so.0(GLIBC_2.3.2)  
Provides: libpthread.so.0(GLIBC_2.3.3)  
Provides: libresolv.so.2  
Provides: libresolv.so.2(GLIBC_2.0)  
Provides: libresolv.so.2(GLIBC_2.2)  
Provides: libresolv.so.2(GLIBC_2.3.2)  
Provides: librt.so.1  
Provides: librt.so.1(GLIBC_2.1)  
Provides: librt.so.1(GLIBC_2.2)  
Provides: libthread_db.so.1  
Provides: libthread_db.so.1(GLIBC_2.1.3)  
Provides: libthread_db.so.1(GLIBC_2.2.3)  
Provides: libthread_db.so.1(GLIBC_2.3)  
Provides: libthread_db.so.1(GLIBC_2.3.3)  
Provides: libutil.so.1  
Provides: libutil.so.1(GLIBC_2.0)  
Provides: glibc 
%prep
%build
%install
echo 'This is only a virtual package, please install your distribution glibc.rpm or equivalent'> %{i}/README 
