### RPM cms openid-client CERNOIDv01

## INITENV +PATH PYTHONPATH %i/lib/python%{pythonv}`echo $PYTHON_VERSION | cut -d. -f 1,2`/site-packages
%define pythonv %(echo $PYTHON_VERSION | cut -d. -f 1,2)

# Needs python >= 2.6
Requires: python py2-pycrypto cherrypy
Source: http://openidenabled.com/files/python-openid/packages/python-openid-2.2.4.tar.gz

%prep
%setup -n python-openid-2.2.4

%build

%install
python setup.py install --prefix=%i
# Perhaps the following is needed to fix python source headers
perl -p -i -e "s|^#!.*python(.*)|#!/usr/bin/env python$1|" `grep -r -e "^#\!.*python.*" %i | cut -d: -f1`

# The %i/etc/profile.d/init.sh|csh will be automatically generated by cmsBuild
#rm -rf %i/etc/profile.d
#mkdir -p %i/etc/profile.d

#%post
# relocation is needed otherwise it will use the path from the building machine 
# when sourcing dependencies  
#%{relocateConfig}etc/profile.d/dependencies-setup.sh
#%{relocateConfig}etc/profile.d/dependencies-setup.csh

#%files
#%i/
