### RPM cms rpm-verify RPMVERIFY_0_2
Source: cvs://:pserver:anonymous@cmscvs.cern.ch:2401/cvs_server/repositories/CMSSW?passwd=AA_:yZZ3e&strategy=export&nocache=true&module=UserCode/DiegoGomes&export=%{n}&&tag=-r%{v}&output=/%{n}.tar.gz

%prep
%setup -T -b 0 -n %{n}

%build

%install
mkdir -p %i/bin
cp -pf %_builddir/%{n}/rpm-verify.sh %i/bin/
chmod 755 %i/bin/rpm-verify.sh
rm -rf %i/etc/profile.d
mkdir -p %i/etc/profile.d

(echo "#!/bin/sh"; \
 echo "source $RPM_ROOT/etc/profile.d/init.sh") > %{i}/etc/profile.d/dependencies-setup.sh

(echo "#!/bin/tcsh"; \
 echo "source $RPM_ROOT/etc/profile.d/init.csh") > %{i}/etc/profile.d/dependencies-setup.csh

# The %i/etc/profile.d/start.sh|csh will be automatically generated by cmsBuild

%post
%{relocateConfig}etc/profile.d/dependencies-setup.sh
%{relocateConfig}etc/profile.d/dependencies-setup.csh

%files
%i/
#%i/rpm-verify.sh

