cvs update -A mongo*
cvs update -A PHEDEX*
cvs update -A dbs*
cvs update -A das*
cvs update -A webtools*
cvs update -A couch*
cvs update -A fmws*
cvs update -A comp.*
cvs update -A spidermonkey*
cvs update -A frontend*
cvs update -A p5-*
cvs update -A apache2*
cvs update -A mod_*
cvs update -A py2-pymongo*
cvs update -A wmcore*
cvs update -A T0Mon*
cvs update -A beautifulsoup.spec
cvs update -A base.spec
cvs update -A cmsweb*
cvs update -A rotatelogs*
cvs update -A py2-*
cvs update -A geoip.spec
cvs update -A dqmgui*
cvs update -A online-patch.spec
cvs update -A adns.spec
cvs update -A pystack.spec
cvs update -A srmcp.spec
cvs update -A cherrypy.spec
cvs update -A erlang.spec
cvs update -A libevent.spec
cvs update -A libyaml.spec
cvs update -A memcached.spec
cvs update -A mysql.spec
cvs update -A sitedb.spec
cvs update -A T0DataSvc.spec
cvs update -A py2-docutils.spec
cvs update -A py2-jinja.spec
cvs update -A py2-pygments.spec
cvs update -A das_docs.spec
cvs update -A subpackage-webdoc.file
cvs update -A online*
cvs update -A stagemanager.spec
cvs update -A apache2-ssl-report-cert*
