### RPM cms web-heartbeat forHEARTBEATr04

# The following tar.gz file will be generated automatically by the CVS server some
# minutes after commiting the files
Source: cvs://:pserver:anonymous@cmscvs.cern.ch:2401/cvs_server/repositories/CMSSW?passwd=AA_:yZZ3e&strategy=export&nocache=true&module=COMP/SITECONF/T1_CH_CERN/Heartbeat&export=srcfromcvs&tag=-r%{v}&output=/srcfromcvs.tar.gz

Requires: wmcore 

%prep
# -T: Disable the automatic unpacking of the archives
# -b 0: only unpack the source directive of the given number, such as –b 0 for source0:, before changing to the directory
# -n srcfromcvs: name the directory as srcfromcvs
%setup -T -b 0 -n srcfromcvs

%build
# It is a script. Nothing to build.

%install
# Copy files files to the destine installation directory.
mkdir -p %i/bin
mkdir -p %i/conf
cp -p %_builddir/srcfromcvs/web-heartbeat.py %i/bin
cp -p %_builddir/srcfromcvs/heartbeat-cfg.py %i/conf
#chmod 755 %i/bin/web-heartbeat.py

# Replace config file template variable in the main script.
perl -p -i -e "s|\@CONFIG_FILE\@|%i/conf/heartbeat-cfg.py|g;" %i/bin/web-heartbeat.py

# The %i/etc/profile.d/init.sh|csh will be automatically generated by cmsBuild
rm -rf %i/etc/profile.d
mkdir -p %i/etc/profile.d

# Add dependencies
(echo "#!/bin/sh"; \
 echo "source $APT_ROOT/etc/profile.d/init.sh"; \
 echo "source $WMCORE_ROOT/etc/profile.d/init.sh") > %{i}/etc/profile.d/dependencies-setup.sh
(echo "#!/bin/tcsh"; \
 echo "source $APT_ROOT/etc/profile.d/init.csh"; \
 echo "source $WMCORE_ROOT/etc/profile.d/init.csh") > %{i}/etc/profile.d/dependencies-setup.csh

%post
%{relocateConfig}bin/web-heartbeat.py
# relocation is needed otherwise it will use the path from the building machine 
# when sourcing dependencies  
%{relocateConfig}etc/profile.d/dependencies-setup.sh
%{relocateConfig}etc/profile.d/dependencies-setup.csh

%files
%i/
%attr(755,-,-) %i/bin/web-heartbeat.py
%config %i/conf/heartbeat-cfg.py

